# Generated by Django 3.2.7 on 2023-03-23 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20230317_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='counsellors',
            field=models.ManyToManyField(blank=True, related_name='counsellors', to=settings.AUTH_USER_MODEL),
        ),
    ]
