# Generated by Django 3.2.7 on 2023-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_counsellors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
