# Generated by Django 3.2.7 on 2023-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contactID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='emailID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recoSub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recoTest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
