# Generated by Django 3.2.7 on 2023-03-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230328_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='India_Abroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='recoSub',
            new_name='dreamCareer',
        ),
        migrations.AddField(
            model_name='room',
            name='majorPlan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='recoUniv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='emailID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='India_Abroad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.india_abroad'),
        ),
    ]
