# Generated by Django 3.2.7 on 2023-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230328_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='recoTest',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
