# Generated by Django 3.2.7 on 2023-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_recotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='emailID',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
