# Generated by Django 3.2.7 on 2023-03-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contactID',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='dreamCareer',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='emailID',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='majorPlan',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='recoTest',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='recoUniv',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='subjects',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='summary',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
